language: python

python:
  - "2.7"

# install dependencies
install:
  - "pip install -r container/requirements.txt"

# run tests
script:
    - py.test tests
    - py.test informer --flake
    - py.test tests --cov informer
    # - python setup.py sdist bdist_wheel