application:
    build: containers/application/python3/
    working_dir: /usr/src/app
    volumes:
        - ./:/usr/src/app
    ports:
        - "8000:8000"

legacy:
    build: containers/application/python2
    working_dir: /usr/src/app
    volumes:
        - ./:/usr/src/app
    ports:
        - "8000:8000"

sample:
    build: containers/sample
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./sample/sample/:/usr/src/app
        - ./informer/:/usr/src/app/informer
    ports:
        - "8000:8000"
    links:
        - postgres

interface:
    build: containers/interface
    working_dir: /usr/src/app
    volumes:
        - ./informer/static/django_informer/:/usr/src/app

postgres:
    image: postgres:9.4.5
