application:
    build: containers/application/python3/
    working_dir: /usr/src/app
    volumes:
        - ./:/usr/src/app
    ports:
        - "8000:8000"
    links:
        - postgres

legacy:
    build: containers/application/python2
    working_dir: /usr/src/app
    volumes:
        - ./:/usr/src/app
    ports:
        - "8000:8000"
    links:
        - postgres

nginx:
    build: containers/nginx
    volumes:
        - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/informer.conf
        - ./informer/static/:/usr/share/nginx/html
    ports:
        - "4000:8080"
    links:
        - sample

sample:
    build: containers/sample
    working_dir: /usr/src/app
    command: gunicorn --bind "0.0.0.0:8000" --workers 4 --worker-class "gevent" --reload sample.wsgi
    volumes:
        - ./sample/sample/:/usr/src/app
        - ./informer/:/usr/src/app/informer
    links:
        - postgres

node:
    build: containers/node
    working_dir: /usr/src/app
    volumes:
        - ./informer/static/django_informer/:/usr/src/app

postgres:
    image: postgres:9.5.1
